FROM ubuntu:18.04

COPY . /aboat-vrgp-adapter

RUN apt-get update
RUN apt-get install -y build-essential cmake

RUN cd /aboat-vrgp-adapter && mkdir build && cd build && cmake .. && make
CMD /aboat-vrgp-adapter/build/adapter
