FROM ubuntu:18.04

COPY . /aboat-vrgp-adapter

RUN apt-get update
RUN apt-get install -y build-essential cmake git libboost-all-dev

RUN git clone https://github.com/zaphoyd/websocketpp /aboat-vrgp-adapter/websocketpp

RUN cd /aboat-vrgp-adapter && mkdir build && cd build && cmake .. && make
CMD /aboat-vrgp-adapter/build/adapter
